ingress:
  enabled: true
  path: /
  hosts:
    - registry.nico.vagrantk3s.dopl.uk
  tls:
    - hosts:
      - registry.nico.vagrantk3s.dopl.uk
      secretName: docker-registry-tls-cert
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: acme-dns-issuer-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # important pour mettre une max body size illimitée pour nginx et pouvoir pousser des grosses images de plusieurs Gio
persistence:
  enabled: true
  size: 10Gi
service:
  port: 5000
  type: ClusterIP
replicaCount: 1