controller:
  ingress:
    enabled: true
    paths: []
    apiVersion: "networking.k8s.io/v1"
    hostName: jenkins.nico.vagrantk3s.dopl.uk
    tls:
      - hosts:
        - jenkins.nico.vagrantk3s.dopl.uk
        secretName: jenkins-tls-cert
    annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: acme-dns-issuer-prod
  jenkinsAdminEmail: nico@lapin.fr
  installPlugins:
    - configuration-as-code:1.51
    - job-dsl:1.77
    - kubernetes:1.30.1
    - blueocean:1.24.7
    - ansible:1.1
    - ansicolor:1.0.0
    - ssh-slaves:1.33.0