apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-token
  namespace: cert-manager
data:
  # insert your DO access token here encoded in base64
  access-token: "c7beef98f748522df341eb311df36600f814301397550ce6a510643aa9931228"
  # access-token: "YzdiZWVmOThmNzQ4NTIyZGYzNDFlYjMxMWRmMzY2MDBmODE0MzAxMzk3NTUwY2U2YTUxMDY0M2FhOTkzMTIyOAo"
