---
apiVersion: rbac.authorization.k8s.io/v1 # On déclare une authorisation
kind: ClusterRole
metadata:
  name: jenkins-admin
rules: # On précise les authorisations voulu
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount # On donne un nom au processus qui va être lancée dans le namespace jenkins
metadata:
  name: jenkins-admin
  namespace: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # On lie le nom donnée au processus avec l'authorisation
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-admin
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: jenkins